
# GITCONFIG

- name: Touch ~/.gitconfig
  ansible.builtin.file:
    path: "{{ home }}/.gitconfig"
    state: touch
    mode: '0600'

- name: Read gitconfig into a variable
  set_fact:
    gitconfig: "{{ lookup('file', 'templates/gitconfig.j2') }}"

- name: Insert/Update ~/.gitconfig
  ansible.builtin.blockinfile:
    path: "{{ home }}/.gitconfig"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    backup: yes
    block: |
      {{ gitconfig }}


# VIM

- name: Touch ~/.vimrc
  ansible.builtin.file:
    path: "{{ home }}/.vimrc"
    state: touch
    mode: '0644'

- name: Read vimrc into a variable
  set_fact:
    vimrc: "{{ lookup('file', 'templates/vimrc.j2') }}"

- name: Insert/Update ~/.vimrc
  ansible.builtin.blockinfile:
    path: "{{ home }}/.vimrc"
    marker: "\" {mark} ANSIBLE MANAGED BLOCK"
    backup: yes
    block: |
      {{ vimrc }}

# TMUX

- name: Touch ~/.tmux.conf
  ansible.builtin.file:
    path: "{{ home }}/.tmux.conf"
    state: touch
    mode: '0644'

- name: Read tmux.conf into a variable
  set_fact:
    tmux: "{{ lookup('file', 'templates/tmux.conf.j2') }}"

- name: Insert/Update ~/.tmux.conf
  ansible.builtin.blockinfile:
    path: "{{ home }}/.tmux.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    backup: yes
    block: |
      {{ tmux }}
