- name: Create a .backups dir if it does not exist
  ansible.builtin.file:
    path: "{{ backups }}"
    state: directory
    mode: '0755'

#----------------
# ZSH
#----------------

- name: Touch ~/.zshrc
  ansible.builtin.file:
    path: "{{ zshrc }}"
    state: touch
    mode: '0644'

- name: Read zshrc.conf into a variable
  set_fact:
    zshrc_contents: "{{ lookup('file', 'templates/zshrc.j2') }}"

- name: Insert/Update ~/.zshrc.conf
  ansible.builtin.blockinfile:
    path: "{{ zshrc }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    backup: yes
    block: |
      {{ zshrc_contents }}

#----------------
# GITCONFIG
#----------------

- name: Touch ~/.gitconfig
  ansible.builtin.file:
    path: "{{ git_config }}"
    state: touch
    mode: '0600'

- name: Read gitconfig into a variable
  set_fact:
    gitconfig_contents: "{{ lookup('file', 'templates/gitconfig.j2') }}"

- name: Insert/Update ~/.gitconfig
  ansible.builtin.blockinfile:
    path: "{{ git_config }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    backup: yes
    block: |
      {{ gitconfig_contents }}

#----------------
# VIM
#----------------

- name: Touch ~/.vimrc
  ansible.builtin.file:
    path: "{{ home }}/.vimrc"
    state: touch
    mode: '0644'

- name: Read vimrc into a variable
  set_fact:
    vimrc_contents: "{{ lookup('file', 'templates/vimrc.j2') }}"

- name: Insert/Update ~/.vimrc
  ansible.builtin.blockinfile:
    path: "{{ vimrc }}"
    marker: "\" {mark} ANSIBLE MANAGED BLOCK"
    backup: yes
    block: |
      {{ vimrc_contents }}

#----------------
# TMUX
#----------------

- name: Touch ~/.tmux.conf
  ansible.builtin.file:
    path: "{{ tmux_conf }}"
    state: touch
    mode: '0644'

- name: Read tmux.conf into a variable
  set_fact:
    tmux_contents: "{{ lookup('file', 'templates/tmux.conf.j2') }}"

- name: Insert/Update ~/.tmux.conf
  ansible.builtin.blockinfile:
    path: "{{ tmux_conf }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    backup: yes
    block: |
      {{ tmux_contents }}
