
# GITCONFIG

- name: Touch .gitconfig
  ansible.builtin.file:
    path: "{{ home }}/.gitconfig"
    state: touch
    mode: u+rw,g-wx,o-rwx
    mode: '0600'

- name: Read gitconfig into a variable
  set_fact:
    gitconfig: "{{ lookup('file', 'templates/gitconfig.j2') }}"

- name: Insert/Update gitconfig
  ansible.builtin.blockinfile:
    path: "{{ home }}/.gitconfig"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    backup: yes
    block: |
      {{ gitconfig }}
