
# GITCONFIG

- name: Touch .gitconfig
  ansible.builtin.file:
    path: "{{ home }}/.gitconfig"
    state: touch
    mode: '0600'

- name: Read gitconfig into a variable
  set_fact:
    gitconfig: "{{ lookup('file', 'templates/gitconfig.j2') }}"

- name: Insert/Update gitconfig
  ansible.builtin.blockinfile:
    path: "{{ home }}/.gitconfig"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    backup: yes
    block: |
      {{ gitconfig }}


# VI

- name: Touch .vimrc
  ansible.builtin.file:
    path: "{{ home }}/.vimrc"
    state: touch
    mode: '0644'

- name: Read vimrc into a variable
  set_fact:
    vimrc: "{{ lookup('file', 'templates/vimrc.j2') }}"

- name: Insert/Update gitconfig
  ansible.builtin.blockinfile:
    path: "{{ home }}/.vimrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    backup: yes
    block: |
      {{ vimrc }}
